c4:
	g++ -O4 -Wall -pedantic main.cpp bitboard.cpp position.cpp evaluate.cpp search.cpp movegen.cpp -o c4

dbg:
	g++ -g -Wall -pedantic main.cpp bitboard.cpp position.cpp evaluate.cpp search.cpp movegen.cpp -o c4_g 

clean:
	rm c4 c4_g
